### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by BektasTu** [BektasTu/capstone-prephase#1]
## User Story, search bar
As a user
I need an input field 
so that I can search for cities

## Description (Scribble)

<img width="279" alt="Homepage" src="https://user-images.githubusercontent.com/111958591/197200700-dbc81404-a214-4250-8137-487a9c5c0ada.png">

<img width="162" alt="search" src="https://user-images.githubusercontent.com/111958591/197199224-f0063deb-debc-4ddb-b009-469f4f7c6547.png">

## Acceptance criteria
- [ ] if I type text into the input field, i get a list of cities matching the text as I type

## Tasks
- [ ] create a new react app
- [ ] remove unnecessary data
- [ ] add an input search field

## Size
small

**Comment by VladF146** [comment]
As a **user** I need an **input field**  so that I can **search for cities**

**Comment by edanum** [comment]
Die Akzeptanz-Kriterien sind nicht scharf genug, um die Erfüllung zu überprüfen. Eventuell könntest du etwas schreiben, wie:
- if I type text into the input field, i get a list of cities matching the text as I type
oder 
- if I type text into the input field an press submit, I get a list of cities matching the text
oder
- I can type text into the input field (nothing more happenig at this userstory e.g. submit or list of cities)

Aktuell würden alle drei Arten von Search-Feld deine Akzeptanz-Kriterien erfüllen. In der Umsetzung macht es aber einen großen Unterschied.
Setze trotzdem mal den Haken :)

**Comment by Kheirah** [comment]
If this is your first user story, you further need to **have data** if you want to show it to the user (who types something into the input field). If that data comes from an API, you need to fetch it first. If you want to work on dummy data first, you need to create it locally.

Either way, data is something you need to include in your story. Otherwise, you wouldn't be able to search.

Good start though 👍
